apiVersion: v1
kind: Pod
metadata:
  name: servian-updatedb
  labels:
    app: servian-updatedb
spec:
  containers:
  - image: servian/techchallengeapp:latest
    name: servian-updatedb
    args: ['updatedb']
    env:
      # Define the environment variable
      - name: WATCH_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VTT_DBUSER
        valueFrom:
          secretKeyRef:
            name: serviantc-secret
            key: dbuser
      - name: VTT_DBPASSWORD
        valueFrom:
          secretKeyRef:
            name: serviantc-secret
            key: dbpassword

      - name: VTT_DBNAME
        valueFrom:
          configMapKeyRef:
            name: servian-conf
            key: DbName
      - name: VTT_DBPORT
        valueFrom:
          configMapKeyRef:
            name: servian-conf
            key: DbPort
      - name: VTT_DBHOST
        valueFrom:
          configMapKeyRef:
            name: servian-conf
            key: DbHost
      - name: VTT_LISTENHOST
        valueFrom:
          configMapKeyRef:
            name: servian-conf
            key: ListenHost
      - name: VTT_LISTENPORT
        valueFrom:
          configMapKeyRef:
            name: servian-conf
            key: ListenPort
    volumeMounts:
      - name: servian-updatedb
        mountPath: /TechChallengeApp/conf.toml
        subPath: conf.toml
        
  volumes:
  - name: servian-updatedb
    configMap:
      name: servian-conf

      